# Generated by Django 2.1.1 on 2019-03-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('session', models.TextField()),
                ('username', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
